name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          context: .
          file: Dockerfile
          push: true
          registry: ghcr.io
          repository:  Maxjr2/nrs-nginx
          tags: latest
